

<div class="modal-header bg-primary">
    <h5 class="modal-title text-white" id="exampleModalLabel">Agregar Canton</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<form id='form_guardar'  data-accion = 'guardar'>
    <div class="modal-body">

        <div class="row form-group">

                <label for="nombrecanton">Nombre Canton</label>
                <input type="text" name="nombrecanton" id="nombrecanton" class="form-control" >


        </div>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary" id='btn_guardar' >
            Guardar canton
        </button>
    </div>
</form>