<link rel="stylesheet" href="<?=URL_BASE?>/public/assets/css/components.css">

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ADESCO EL BORBOLLON</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="<?=URL_BASE?>/public/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- SweetAlert2 -->
    <link rel="stylesheet" href="<?=URL_BASE?>/public/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="<?=URL_BASE?>/public/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="<?=URL_BASE?>/public/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="<?=URL_BASE?>/public/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="<?=URL_BASE?>/public/dist/css/adminlte.min.css">
    <link rel="stylesheet" href="<?=URL_BASE?>/public/plugins/bootstrap/css/bootstrap.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="<?=URL_BASE?>/public/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="<?=URL_BASE?>/public/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="<?=URL_BASE?>/public/plugins/summernote/summernote-bs4.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="<?=URL_BASE?>/public/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="<?=URL_BASE?>/public/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

    <!-- Navbar -->
    <?= isset($navbar) ? $navbar : ''?>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <?= isset($sidebar) ? $sidebar : ''?>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->

        <!-- Main content -->
        <?=isset($main) ? $main : ''?>

        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <?= isset($footer) ? $footer : ''?>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="<?=URL_BASE?>/public/plugins/jquery/jquery.min.js"></script>
<script src="<?=URL_BASE?>/public/plugins/jquery-3.4.1.min.js"></script>
<script src="<?=URL_BASE?>/public/plugins/select2.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="<?=URL_BASE?>/public/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- DataTables -->
<script src="<?=URL_BASE?>/public/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?=URL_BASE?>/public/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="<?=URL_BASE?>/public/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="<?=URL_BASE?>/public/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="<?=URL_BASE?>/public/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- ChartJS -->
<script src="<?=URL_BASE?>/public/plugins/chart.js/Chart.min.js"></script>
<!-- Sparkline -->
<script src="<?=URL_BASE?>/public/plugins/sparklines/sparkline.js"></script>
<!-- JQVMap -->
<script src="<?=URL_BASE?>/public/plugins/jqvmap/jquery.vmap.min.js"></script>
<script src="<?=URL_BASE?>/public/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
<!-- jQuery Knob Chart -->
<script src="<?=URL_BASE?>/public/plugins/jquery-knob/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="<?=URL_BASE?>/public/plugins/moment/moment.min.js"></script>
<script src="<?=URL_BASE?>/public/plugins/daterangepicker/daterangepicker.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="<?=URL_BASE?>/public/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- Summernote -->
<script src="<?=URL_BASE?>/public/plugins/summernote/summernote-bs4.min.js"></script>
<!-- overlayScrollbars -->
<script src="<?=URL_BASE?>/public/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="<?=URL_BASE?>/public/dist/js/adminlte.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="<?=URL_BASE?>/public/dist/js/pages/dashboard.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="<?=URL_BASE?>/public/dist/js/demo.js"></script>
<!-- SweetAlert2 -->
<script src="<?=URL_BASE?>/public/plugins/sweetalert2/sweetalert2.min.js"></script>
<!-- Toastr -->
<script src="<?=URL_BASE?>/public/plugins/toastr/toastr.min.js"></script>
<!-- DataTables -->
<script src="<?=URL_BASE?>/public/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?=URL_BASE?>/public/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="<?=URL_BASE?>/public/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="<?=URL_BASE?>/public/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="<?=URL_BASE?>/public/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="<?=URL_BASE?>/public/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<!-- JSZip -->
<script src="<?=URL_BASE?>/public/plugins/jszip/jszip.min.js"></script>
<!-- pdfmake -->
<script src="<?=URL_BASE?>/public/plugins/pdfmake/pdfmake.min.js"></script>
<script src="<?=URL_BASE?>/public/plugins/pdfmake/vfs_fonts.js"></script>
<!-- Popper -->
<script src="<?=URL_BASE?>/public/plugins/popper/popper.min.js"></script>



<!-- datatables JS -->
<script type="text/javascript" src="<?=URL_BASE?>/public/plugins/datatables/datatables.min.js"></script>

<!-- para usar botones en datatables JS -->
<script src="<?=URL_BASE?>/public/plugins/datatables/Buttons-1.5.6/js/dataTables.buttons.min.js"></script>
<script src="<?=URL_BASE?>/public/plugins/datatables/JSZip-2.5.0/jszip.min.js"></script>
<script src="<?=URL_BASE?>/public/plugins/datatables/pdfmake-0.1.36/pdfmake.min.js"></script>
<script src="<?=URL_BASE?>/public/plugins/datatables/pdfmake-0.1.36/vfs_fonts.js"></script>
<script src="<?=URL_BASE?>/public/plugins/datatables/Buttons-1.5.6/js/buttons.html5.min.js"></script>
<script src="<?=URL_BASE?>/public/js/utils.js"></script>
<script src="<?=URL_BASE?>/public/js/tablaUsuario.js"></script>
<script src="<?=URL_BASE?>/public/js/Canton.js"></script>
<script src="<?=URL_BASE?>/public/js/Reporte1.js"></script>
<script src="<?=URL_BASE?>/public/js/Consumo.js"></script>
<script src="<?=URL_BASE?>/public/js/tablaCliente.js"></script>



</body>
</html>
