<nav class="main-header navbar navbar-expand navbar-white navbar-light" >
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="admin.phtml" class="nav-link">Inicio</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Contactanos</a>
        </li>
        <li class="nav-item dropdown">
            <a href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">
                <i class="nav-icon fas fa-file"></i>
                Reportes
            </a>
            <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                <li class="nav-item">
                    <a href="Reporte" class="dropdown-item">
                        Consumo Promedio por canton
                    </a>
                </li>
                <li class="nav-item">
                    <a href="Reporte2" class="dropdown-item">
                        Total  recaudado por canton
                    </a>
                </li>
                <!-- los cantones se van a registrar en la misma vista -->
                <li class="nav-item">
                    <a href="Reporte3" class="dropdown-item">
                        Recibo de Pago
                    </a>
                </li>
            </ul>
        </li>
    </ul>


    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <li style="display: flex; justify-content: center; align-items: center">

            <a href="/login/cerrar-sesion" class="nav-link" style="padding: 8px"><i class="nav-icon fas fa-door-open"></i> Cerrar sesion</a>
        </li>
    </ul>
</nav>
