<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        <img src="<?= URL_BASE ?>/public/dist/img/AdminLTELogo.png" alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">Adesco | El Borbollon</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="info">
                <a href="#" class="d-block">
                    <?php
                $sesion = new Session();
                $login = $sesion->get('login');
                echo $login['usuario']
                ?>
                </a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <?php
                $sesion = new Session();
                $login = $sesion->get('login');
                $rol = $login['tipo'];



                if($rol === 'Administrador'):
                ?>
                    <li class="nav-item has-treeview">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-user-friends"></i>
                            <p>
                                Clientes
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="/formCliente" class="nav-link">
                                    <i class="nav-icon fas fa-user-edit"></i>
                                    <p>Registrar Clientes</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="/formCliente/tablaClientes" class="nav-link">
                                    <i class="nav-icon fas fa-table"></i>
                                    <p>Gestionar Clientes</p>
                                </a>
                            </li>
                            <!-- los cantones se van a registrar en la misma vista -->
                            <li class="nav-item">
                                <a href="/Canton" class="nav-link">
                                    <i class="nav-icon fas fa-house-user"></i>
                                    <p>Gestionar Cantones</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-user"></i>
                        <p>
                            Usuarios
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="/formUsuario" class="nav-link">
                                <i class="nav-icon fas fa-user-edit"></i>
                                <p>Registrar Usuarios</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/formUsuario/tablaUsuarios" class="nav-link">
                                <i class="nav-icon fas fa-table"></i>
                                <p>Gestionar Usuarios</p>
                            </a>
                        </li>
                    </ul>
                </li>
                    <li class="nav-header">
                        <i class="nav-icon fas fa-hand-holding-water"></i>
                        <a> Servicio de agua potable</a>
                    </li>
                    <li class="nav-item has-treeview">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-water"></i>
                            <p>
                                Consumo del agua
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="nav-icon fas fa-edit"></i>
                                    <p>Registrar consumo</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="nav-icon fas fa-table"></i>
                                    <p>Ver Consumo del agua</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item has-treeview">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-file-invoice-dollar"></i>
                            <p>
                                Recibo de agua
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="nav-icon fas fa-edit"></i>
                                    <p>crear Recibo de agua</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="nav-icon fas fa-table"></i>
                                    <p>ver Recibo de agua</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="Tarifa" class="nav-link">
                                    <i class="nav-icon fas fa-list"></i>
                                    <p>Tarifa de agua</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item has-treeview">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-file"></i>
                            <p>
                                Reportes
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="Reporte" class="nav-link">
                                    <i class="nav-icon fas fa-circle"></i>
                                    <p>Consumo Promedio por canton</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="nav-icon fas fa-circle"></i>
                                    <p>Reporte 2</p>
                                </a>
                            </li>
                            <!-- los cantones se van a registrar en la misma vista -->
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="nav-icon fas fa-circle"></i>
                                    <p>Reporte 3</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                <?php
                endif

                ?>
                <?php
                $sesion = new Session();
                $login = $sesion->get('login');
                $rol = $login['tipo'];

                    if ($rol === 'Cliente'):
                ?>
                        <li class="nav-header">
                            <i class="nav-icon fas fa-hand-holding-water"></i>
                            <a> Servicio de agua potable</a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="" class="nav-link">
                                <i class="nav-icon fas fa-water"></i>
                                <p>
                                    Consumo del agua
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="/xd" class="nav-link">
                                        <i class="nav-icon fas fa-history"></i>
                                        <p>Historial de consumo</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-file-invoice-dollar"></i>
                                <p>
                                    Recibo de agua
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="nav-icon fas fa-history"></i>
                                        <p>Historial de Recibos</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="nav-icon fas fa-list"></i>
                                        <p>Tarifa de agua</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                <?php

                endif

                ?>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>
