<section>
    <div class="card">
        <div class="card-header" style="background-color: #3085d6">
            <div class="login-logo">
                <a style="color: white; font-size: 50px" ><b>Adesco </b>El Borbollon</a>
            </div>
        </div>
        <div class="card-body">
        <section>
            <img src="<?= URL_BASE ?>/public/dist/img/agua-llave-corte-notimex-770.jpg" class="card-img-bottom">
        </section>

        </div>
        <!-- /.card-body -->
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->
</section>
