<section>
    <div class="card">


        <center>
            <b style="font-size: 25px">RECIBO DE PAGO</b>
            <hr>
            <b style="font-size: 25px">ADESCO EL BORBOLLON</b>
            <hr>
        </center>

        <!--Ejemplo tabla con DataTables-->
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive">

                        <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                            <tr role="row">

                                <th  style="width: 15%">CODIGO</th>
                                <th style="width: 15%">FECHA EMISION</th>
                                <th style="width: 15%">FECHA PAGO</th>
                                <th style="width: 15%">TOTAL A PAGAR</th>
                                <th style="width: 15%">CLIENTE</th>
                                <th style="width: 15%">CANTON</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            $consultas = isset($datos) ? $datos : array();

                            foreach ($consultas as $key => $consulta) {
                                echo "
                    <tr> 
                        <td>".$consulta['codrecibo']."</td>
                        <td>".$consulta['fechaemision']."</td>
                        <td>".$consulta['fecha_pago']."</td>
                         <td>".$consulta['pago']."</td>
                         <td>".$consulta['nombcliente']."</td>
                         <td>".$consulta['nombrecanton']."</td>
                    </tr>
                ";
                            }
                            ?>



                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    <!-- /.card-body -->
    </div>
    <!-- /.card -->
</section>

<div class="modal fade" id="modal_acciones_canton" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content" id="modal-content-body">
        </div>
    </div>
</div>


<script src="<?=URL_BASE?>/public/js/utils.js"></script>
