<?php
$clientes = isset($datos) ? $datos : array();
?>
<section>
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Clientes que no tienen un registro de consumo de este mes </h3>
        </div>
        <div class="card-body">
            <div class="form-group row">

                <div id='div_tabla_cliente' class='table-responsive'>
                    <table id="tabla_cliente_consumo" class="table  table-bordered table-hover">
                        <thead>
                        <tr role="row">
                            <th  style="width: 15%">Codigo</th>
                            <th  style="width: 25%">Nombres</th>
                            <th  style="width: 15%">Dui</th>
                            <th  style="width: 15%">Direccion</th>
                            <th  style="width: 15%">Telefono</th>
                            <th  style="width: 15%">Acciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php


                        foreach ($clientes as $key => $cliente) {

                                echo "
                    <tr>
                        <td>" . $cliente['codcliente'] . "</td>
                        <td>" . $cliente['nombrecliente'] . " " . $cliente['apellidocliente'] . "</td>
                        <td>" . $cliente['dui'] . "</td>
                        <td>" . $cliente['direccion'] . "</td>
                        <td>" . $cliente['telefono'] . "</td>
                        
                        <td style='display: flex; justify-content: center; align-content: space-between'>
                            <button style='margin: 6px' type='button' id ='btn_regconsumo' class='btn btn-warning' 
                            data-toggle='tooltip' data-placement='top'
                            title='' data-original-title='regconsumo' data-id = '" . $cliente['codcliente'] . "'>
                            Registrar consumo
                            </button>
                        </td>
                    </tr>
                ";

                            }

                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</section>
<div class="modal fade" id="modal_acciones_consumo" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content" id="modal-content-body">
        </div>
    </div>
</div>
